```{r}
#| label: load-pkgs
#| message: false

suppressWarnings(library(tidyverse))
library(knitr)
library(lubridate)
library(here)
library(ggridges)
```

## Dataset Setup

```{r}

cats <- read.csv(here("data", "cats_uk_reference.csv"))
cats_usa <- read.csv(here("data", "cats_usa_reference.csv"))
cats
cats_usa
```

```{r}
refs <- read_csv(here("data", "cats_uk.csv"))
refs_usa <- read.csv(here("data","cats_usa.csv"))
cats_all <- read_csv(here("data","cats_all.csv"))
cats_all_new <- read_csv(here("data", "cats_all_new.csv"))


refs
refs_usa
```

```{r}

#cats_australia <- read.csv(here("data","cats_australia.csv"))
#cats_australia_refs <- read.csv("data","cats_australia_reference")'
colnames(refs_usa) <- gsub("[.]", "_", colnames(refs_usa))
colnames(cats_usa) <- gsub("[.]", "_", colnames(cats_usa))

 <- cats_usa %>%
  separate(
    animal_comments,
    into = c("hunt", "prey_p_month"),
    sep = "; ",
    remove = FALSE
  )

cats_usa <- cats_usa %>%
  separate(
    animal_comments,
    into = c("hrs_indoors", "n_cats"),
    sep = "; ",
    remove = FALSE
  )

ref_uk_usa <- inner_join(refs,refs_usa, by="event_id")
cats_uk_usa <- inner_join(cats,cats_usa, by="tag_id")
%>% 
  #mutate(country = ifelse(is.na(country), "Unknown", country))
```

```{r}

cats_all |>
  group_by(tag_id) |>
  summarise(avg_ground_speed=mean(ground_speed))
```

```{r}

cats_speed <- group_by(cats_uk_usa_refs, tag_id) |> summarise(avg_ground_speed = mean(ground_speed.x))
```

```{r}

cats <- left_join(cats, cats_speed, by=c("tag_id" = "tag_id"))
cats
```

```{r}
write.table(cats , 
            file = here("data", "cats_merged.csv"), 
            sep=",", row.names=FALSE)
```

```{r}

cats_uk_usa[cats_uk_usa$n_cats > 4,c("n_cats")]
```

```{r}

```

## Plots

```{r, warning=FALSE}

cats_uk_usa |>
  ggplot(aes(x=as.character(n_cats), y=prey_p_month)) +
  geom_jitter(aes(size=age_years, color=avg_ground_speed)) +
  # geom_violin() +
  scale_color_gradient(low = "pink2", high = "black") +
  theme_minimal()

# The hunting pattern is lonely cats is similar to the cats who live together. only difference being, the cats who are lonely only became better as they aged, but the cats who live together, started hunting more as they were young, and stopped as they got older
```

```{r, warning=FALSE}


# cats[cats$animal_reproductive_condition %in% c("Neutered", "Spayed"),] |>
#   ggplot(aes(x=prey_p_month, y=hrs_indoors, color=animal_reproductive_condition)) +
#   geom_jitter() +
#   # geom_smooth(se=FALSE) +
#   # geom_line() +
#   theme_minimal()

cats_all |>
  mutate(
    is_neutered = case_when(
      animal_reproductive_condition %in% c("Neutered", "Spayed") ~ "Yes",
      TRUE ~ "No"
    )
  ) |>
  group_by(is_neutered, hrs_indoors) |>
  summarize(avg_prey = mean(prey_p_month), avg_age=mean(age_years), 
            .groups = "drop") |>
  drop_na() |>
  ggplot(aes(x=avg_prey, y=hrs_indoors, color=is_neutered)) +
  geom_jitter() +
  # geom_smooth(se=FALSE) +
  #geom_line(size=0.8) +
  theme_minimal()
```

```{r}


cats_all_new |>
  mutate(
    is_neutered = case_when(
      animal_reproductive_condition %in% c("Neutered", "Spayed") ~ "Yes",
      TRUE ~ "No"
    )
  ) |>
  #group_by(is_neutered) |>
  #summarize(sum_hrs = sum(hrs_indoors), avg_age=mean(age_years), 
            #.groups = "drop") |>
  # drop_na() |>
  ggplot(aes(x=cats_all$age_years, y=cats_all$prey_p_month, color = animal_reproductive_condition)) +
  geom_jitter(size = 2, alpha = 1) +
  facet_wrap(~cats_all_new$animal_reproductive_condition) +
  # geom_smooth(se=FALSE
  #geom_dotplot() +
  theme_minimal()
```

```{r}

library(hrbrthemes)
library(GGally)
# library(viridis) 

cats_all |>
  mutate(
    is_neutered = case_when(
      animal_reproductive_condition %in% c("Neutered", "Spayed") ~ "Yes",
      TRUE ~ "No"
    )
  ) |>
  group_by(is_neutered, prey_p_month) |>
  summarize(sum_hrs = sum(hrs_indoors), avg_age=mean(age_years),
            .groups = "drop") |>
  # drop_na() |>
  ggparcoord(
      columns = 2:3, groupColumn=1, #order = "allClass",
      scale="uniminmax",
      showPoints = TRUE, 
      title = "Parallel Coordinate Plot for the Iris Data",
      alphaLines = 0.3
      ) + 
      # scale_color_viridis(discrete=TRUE) +
    scale_color_manual(values=c("red", "black")) +
    theme_ipsum()+
    theme(
      plot.title = element_text(size=10)
    )
```

```{r}

cats_all_new |>
  ggplot(aes(cats_all$age_years, prey_p_month, color= animal_reproductive_condition)) +
  geom_jitter(alpha = 0.5, size = 2) +
  #facet_wrap(~cats_all_new$animal_reproductive_condition) +
  labs(
    x = "Age",
    y = "Prey per month"
  )
```

```{r}

cats_all %>%
  ggplot(aes(x = hrs_indoors, y = prey_p_month, color = animal_reproductive_condition)) +
  geom_jitter(alpha = 1, size = 4) +
  #facet_wrap(~animal_sex) +
  labs(
    x = "Hours indoors",
    y = "Prey per month"
  ) +
  scale_color_manual(values = c("Spayed" = "#D669FF", "Fixed" = "black", "Neutered" = "#58A6F0", "Not fixed" = "#4BAF0B" ))  # Adjust colors as needed
```

```{r}

cats_all_new %>%
  ggplot(aes(x = hrs_indoors, y = prey_p_month, color = animal_reproductive_condition)) +
  geom_boxplot() +
  #facet_wrap(~animal_sex) +
  labs(
    x = "Hours indoors",
    y = "Prey per month"
  )
  
  #scale_color_manual(values = c("Spayed" = "#D669FF", "Fixed" = "black", "Neutered" = "#58A6F0", "Not fixed" = "#4BAF0B" ))  
```

```{r}

cats_all_new |>
  mutate(
    is_neutered = case_when(
      animal_reproductive_condition %in% c("Neutered", "Spayed") ~ "Yes",
      TRUE ~ "No"
    )
  ) |>
  ggplot(aes(x=cats_all_new$age_years,prey_p_month, shape = cats_all_new$animal_reproductive_condition, color = animal_reproductive_condition)) +
  geom_jitter(alpha = 0.5, size = 3) +
  scale_color_manual(values = c("Fixed" = "pink2", "Unneutered" = "blue3")) +
  theme_minimal() + 
  labs(
    x = "Cat age in years",
    y = "Prey per month",
  )
```

```{r warning=FALSE, message=FALSE}

cats_all_new |>
  ggplot(aes(x=prey_p_month,y=animal_reproductive_condition, 
             fill = factor(stat(quantile)))) +
  stat_density_ridges(quantile_lines = TRUE, 
                      quantiles = 3, 
                      alpha = 0.5,
                      geom = "density_ridges_gradient", 
                      calc_ecdf = TRUE) +
  #scale_fill_viridis_d() +
  #scale_fill_manual(values = c("#950A9B","#259703","skyblue")) +
    scale_fill_manual(values = c("skyblue2","brown","#259703")) +
  scale_x_continuous(breaks = seq(0,23,5))+
  facet_wrap(~cats_all_new$study_site) +
  labs(
    title = "How are cats impacted by their reproductive condition?",
    subtitle = "Categorized by different countries",
    x = "Prey per month",
    y = "Annimal reproductive condition"
  ) +
  theme_minimal()
```

```{r}

library(dlookr)

#find out mean value for each country
#We will hide the legend

describe(cats_all_new)
```

```{r}

cats_fixed <- filter(cats_all_new,cats_all_new$animal_reproductive_condition == "Fixed")
cats_unn <- filter(cats_all_new,cats_all_new$animal_reproductive_condition == "Unneutered")

library(viridis)

cats_fixed |>
  ggplot(aes(x=prey_p_month, y = age_years, color = animal_reproductive_condition)) +
  geom_jitter(data = filter(cats_all_new, animal_reproductive_condition == "Fixed"), aes(size = 2,alpha = 0.5)) +
  geom_jitter(data = filter(cats_all_new, animal_reproductive_condition == "Unneutered"), aes(size = 2)) +
   scale_fill_viridis(palette = "colorblind") +
  labs(
    x = "Prey per month",
    y = "Age years"
  )
```

```{r}

cats_fixed |>
  ggplot(aes(x=prey_p_month, y = age_years, color = animal_reproductive_condition)) +
  geom_hex(data = filter(cats_all_new, animal_reproductive_condition == "Fixed"), aes(size = 2,alpha = 0.5)) +
  geom_hex(data = filter(cats_all_new, animal_reproductive_condition == "Unneutered"), aes(size = 2)) +
  labs(
    x = "Prey per month",
    y = "Age years"
  )


cats_all_new |>
  ggplot(aes(x=prey_p_month, y = age_years, color = animal_reproductive_condition)) +
  geom_hex(data = filter(cats_all_new, animal_reproductive_condition == "Fixed",bins = 20)
```

```{r}

cats_all_new |>
  ggplot(aes(x=prey_p_month,y = age_years, fill = animal_reproductive_condition)) +
geom_hex(data = filter(cats_all_new, animal_reproductive_condition == "Fixed"), bins = 15) +
geom_hex(data = filter(cats_all_new, animal_reproductive_condition == "Unneutered"), bins = 20) +
scale_fill_manual(values = c("Fixed" = "black", "Unneutered" = "pink"))

```

\
\
\
